use crate::agent::plan::plan_task;
use crate::agent::safe_paths::validate_patch_path;
use crate::agent::storage::{id, load_json, memory_path, now_unix, save_json_pretty};
use crate::agent::task::{load_task, update_task};
use crate::contracts::{
    AgentTaskStatus, PatchOp, PatchOperationKind, PatchProposal, ProposalStatus,
};

pub fn propose_task(
    project_root: &str,
    memory_root: &str,
    task_id: &str,
) -> Result<PatchProposal, String> {
    let mut task = load_task(memory_root, task_id)?;
    let plan = match task.plan_id.clone() {
        Some(plan_id) => load_json(&memory_path(
            memory_root,
            &["plans", &format!("{plan_id}.json")],
        ))?,
        None => plan_task(project_root, memory_root, task_id)?,
    };
    let lower = task.goal.to_ascii_lowercase();
    let mut blockers = Vec::new();
    let patch_ops = if lower.contains("doc")
        || lower.contains("readme")
        || lower.contains("опис")
        || lower.contains("док")
    {
        let path = format!("docs/agent_task_{task_id}.md");
        vec![PatchOp {
            path,
            op: PatchOperationKind::CreateFile,
            description: "Create deterministic task documentation.".into(),
            content: Some(format!(
                "# Agent Task {task_id}\n\nGoal: {}\n\nGenerated by EVE governed production agent.\n",
                task.goal
            )),
            find: None,
            replace: None,
        }]
    } else if lower.contains("test") || lower.contains("tests") || lower.contains("провер") {
        let safe_task = task_id.replace('-', "_");
        vec![PatchOp {
            path: format!("tests/agent_generated_{safe_task}_tests.rs"),
            op: PatchOperationKind::CreateFile,
            description: "Create deterministic compile-safe agent test fixture.".into(),
            content: Some(format!(
                "#[test]\nfn agent_generated_{safe_task}_compiles() {{\n    assert!(true);\n}}\n"
            )),
            find: None,
            replace: None,
        }]
    } else {
        blockers.push("task_requires_manual_decomposition".into());
        Vec::new()
    };
    let mut proposal = PatchProposal {
        proposal_id: id("proposal"),
        task_id: task_id.into(),
        plan_id: plan.plan_id,
        status: if blockers.is_empty() {
            ProposalStatus::AwaitingApproval
        } else {
            ProposalStatus::Refused
        },
        created_at: now_unix(),
        updated_at: now_unix(),
        goal: task.goal.clone(),
        summary: "Deterministic rule-based patch proposal.".into(),
        proposer: "rule_based".into(),
        llm_used: false,
        files_to_change: patch_ops.iter().map(|op| op.path.clone()).collect(),
        forbidden_paths: task.forbidden_paths.clone(),
        risk_level: task.risk_level.clone(),
        approval_required: true,
        approved: false,
        approved_at: None,
        patch_ops,
        warnings: Vec::new(),
        blockers,
    };
    validate_patch_proposal(&mut proposal);
    save_json_pretty(
        &memory_path(
            memory_root,
            &["proposals", &format!("{}.json", proposal.proposal_id)],
        ),
        &proposal,
    )?;
    save_json_pretty(
        &memory_path(memory_root, &["proposals", "latest_proposal.json"]),
        &proposal,
    )?;
    task.status = if proposal.status == ProposalStatus::Refused {
        AgentTaskStatus::Blocked
    } else {
        AgentTaskStatus::Proposed
    };
    task.proposal_id = Some(proposal.proposal_id.clone());
    update_task(memory_root, task)?;
    Ok(proposal)
}

pub fn validate_patch_proposal(proposal: &mut PatchProposal) {
    for op in &proposal.patch_ops {
        if let Err(error) = validate_patch_path(&op.path) {
            proposal.blockers.push(error.to_string());
        }
        if matches!(op.op, PatchOperationKind::ReplaceExactText)
            && (op.find.is_none() || op.replace.is_none())
        {
            proposal
                .blockers
                .push(format!("invalid_replace_exact_text:{}", op.path));
        }
    }
    if proposal.approved && proposal.approved_at.is_none() {
        proposal.blockers.push("proposal_self_approved".into());
    }
    proposal.blockers.sort();
    proposal.blockers.dedup();
    if !proposal.blockers.is_empty() {
        proposal.status = ProposalStatus::Refused;
    }
}

pub fn load_proposal(memory_root: &str, proposal_id: &str) -> Result<PatchProposal, String> {
    load_json(&memory_path(
        memory_root,
        &["proposals", &format!("{proposal_id}.json")],
    ))
}

pub fn save_proposal(memory_root: &str, proposal: &PatchProposal) -> Result<(), String> {
    save_json_pretty(
        &memory_path(
            memory_root,
            &["proposals", &format!("{}.json", proposal.proposal_id)],
        ),
        proposal,
    )?;
    save_json_pretty(
        &memory_path(memory_root, &["proposals", "latest_proposal.json"]),
        proposal,
    )
}

pub fn print_propose_task(
    project_root: &str,
    memory_root: &str,
    task_id: &str,
) -> Result<String, String> {
    let proposal = propose_task(project_root, memory_root, task_id)?;
    if proposal.status == ProposalStatus::Refused {
        return Ok(format!(
            "proposal refused\ntask_id={}\nreason={}\nblockers={}",
            proposal.task_id,
            proposal
                .blockers
                .first()
                .map(String::as_str)
                .unwrap_or("unknown"),
            proposal.blockers.join(",")
        ));
    }
    Ok(format!(
        "proposal created\nproposal_id={}\ntask_id={}\nproposer={}\nllm_used={}\nstatus=AwaitingApproval\nfiles_to_change={}\napproval_required=true",
        proposal.proposal_id,
        proposal.task_id,
        proposal.proposer,
        proposal.llm_used,
        proposal.files_to_change.join(",")
    ))
}
