use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RecombinedHypothesis {
    pub hypothesis_id: String,
    pub source_patterns: Vec<String>,
    pub avoided_risks: Vec<String>,
    pub target_objective: String,
    pub suggested_mutation_kind: String,
    pub suggested_target: String,
    pub reason_ru: String,
    pub portfolio_reason_ru: String,
    pub selected_strategy: String,
    pub policy_reason_ru: String,
    pub expected_gain: f32,
    pub estimated_risk: f32,
    pub confidence: f32,
    pub diversity_bonus: f32,
    pub saturation_penalty: f32,
    pub repeated_target_penalty: f32,
    pub final_recombination_score: f32,
    pub strategy_bonus: f32,
    pub strategy_saturation_penalty: f32,
    pub quality_bonus: f32,
    pub novelty_score: f32,
    pub useful_delta_score: f32,
    pub duplicate_suppression_score: f32,
    pub regression_avoidance_score: f32,
    pub coverage_proxy_score: f32,
    pub quality_score: f32,
    pub final_strategy_score: f32,
}
